project_dir := justfile_directory()
build_dir := project_dir + "/build"
cflags := "-std=c99 -Wall -Werror -Wextra -pedantic"

@default:
	just --list

@build:
	mkdir -p {{build_dir}}
	zig cc {{cflags}} -o {{build_dir}}/monkey -lreadline src/main.c 

@run: build
	{{build_dir}}/monkey

@test:
	mkdir -p {{build_dir}}

	zig cc {{cflags}} -o {{build_dir}}/lexer_test test/lexer_test.c
	{{build_dir}}/lexer_test

	zig cc {{cflags}} -o {{build_dir}}/parser_test test/parser_test.c
	{{build_dir}}/parser_test
